[package]
name = "dec07"
version = "0.1.0"
authors = ["Christofer Kanljung <christofer.kanljung@zenuity.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"

